name: Run Unit Test - IGNITE API SOLID

on: [push]

jobs:
  run-unit-test:
    name: Run Unit Test
    runs-on: ubuntu-latest

    step:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"

      - run: npm cli
      - run: npm run test
